#!/bin/bash

# Odstranění aliasů z /etc/bash.bashrc
sed -i '/alias Mojang=/d' /etc/bash.bashrc
sed -i '/alias mojang=/d' /etc/bash.bashrc
sed -i '/alias MOJANG=/d' /etc/bash.bashrc
sed -i '/alias Debian=/d' /etc/bash.bashrc
sed -i '/alias debian=/d' /etc/bash.bashrc
sed -i '/alias DEBIAN=/d' /etc/bash.bashrc
sed -i '/source ~/.bashrc/d' /etc/bash.bashrc

# Odstranění binárních souborů, pokud existují
if [ -f /usr/local/bin/Mojang ]; then
    rm -f /usr/local/bin/Mojang
fi

if [ -f /usr/local/bin/Debian ]; then
    rm -f /usr/local/bin/Debian
fi

exit 0
